# traefik + nginx + php-fpm + mysql + phpmyadmin + portainer
version: "3.4"
services:
  nginx-lasante:
    container_name: ${DOMAIN_NAME}_nginx-${WEBSITE_NAME}
    image: nginx:1.17.10
    volumes:
      - ../public:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    networks:
      - proxy
networks:
  proxy:
    external: true
