name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd public/
        docker build . --file Dockerfile --tag digitalonearth/delouvien
        docker build . --file Dockerfile.nginx --tag digitalonearth/delouvien-nginx
        docker push digitalonearth/delouvien
        docker push digitalonearth/delouvien-nginx
    
